<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdnonjg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdnonjg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRdnonjg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRdnonjg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRdnonjg\appProdProjectContainer(array(
    'container.build_hash' => 'Rdnonjg',
    'container.build_id' => '86c81938',
    'container.build_time' => 1520349965,
));
