AppBundle\Entity\Subtasca:
    type: entity
    table: subtasca
    indexes:
        idtasca:
            columns:
                - idtasca
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        descripcion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        fechaInicio:
            type: date
            nullable: false
            column: fecha_inicio
        fechaFin:
            type: date
            nullable: false
            column: fecha_fin
    manyToOne:
        idtasca:
            targetEntity: Tasca
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtasca:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
