<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9li7iti\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9li7iti/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9li7iti.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9li7iti\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9li7iti\appDevDebugProjectContainer(array(
    'container.build_hash' => '9li7iti',
    'container.build_id' => 'f4aa1e39',
    'container.build_time' => 1520344459,
));
